# Generated by Django 6.0.5 on 2026-05-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level_number', models.PositiveIntegerField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('required_score', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['subject', 'level_number'],
                'unique_together': {('subject', 'level_number')},
            },
        ),
    ]
