# Generated by Django 6.0.5 on 2026-05-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0, help_text='Total XP earned for this level (best attempt).'),
        ),
    ]
